### ISSUE TITLE
[BUG] Weird Shadow On Multi-Line TextBox's

### ISSUE THREAD

**Issue by ImInTheICU** [boatbomber/Highlighter#29]
A strange shadow appears and grows noticeably larger after typing some code, then deleting a few lines below it.

TextBox inside of ScrollingFrame.

https://user-images.githubusercontent.com/111275373/233818208-08cba463-b5d3-441a-8482-0b892ca5488d.mp4

**Comment by jmesrje** [comment]
Can confirm, also having this issue.

**Comment by boatbomber** [comment]
I'm struggling to repro this issue. Can you share your OS, Resolution, Scaling, and ideally the UI instances as an rbxm?

**Comment by boatbomber** [comment]
I can make this happen when the TextObject has a UIPadding, but your video doesn't appear to have padding so it seems like an unrelated issue.

**Comment by 2406mmartin** [comment]
> I can make this happen when the TextObject has a UIPadding, but your video doesn't appear to have padding so it seems like an unrelated issue.

You can also replicate it by using Automatic Scaling, which I assume was used.

**Comment by ImInTheICU** [comment]
Where still trying to solve this?

**Comment by boatbomber** [comment]
Does this persist in the latest version?

**Comment by LovreDev** [comment]
I can confirm that this is still happening, I'm using a textbox and setting textObject to the textbox.

**Comment by boatbomber** [comment]
Please share a place or model file that reproduces this issue!

**Comment by LovreDev** [comment]
Here's a video and rbxm file of the issue:
https://github.com/boatbomber/Highlighter/assets/127324434/60ccd1a8-9167-41c1-a9da-84a110dd0564
[PluginFile.zip](https://github.com/boatbomber/Highlighter/files/12232745/PluginFile.zip)

**Comment by boatbomber** [comment]
Thank you for the repro! It was extremely helpful. This is fixed (at least, by my testing) in 0.8.2!
