### ISSUE TITLE
Lexer matches unicode, but doesn't catch it.

### ISSUE THREAD

**Issue by Exunys** [boatbomber/Highlighter#3]
Title says it all, I am using **src/lexer/init.lua**. Here's a quick example:

`⭮⽥⻶ⓞ⠏Ⱈ⵼⇠⺀❜⍨ↇ⡧⚏ⷔ⸂␳⋡⒀⻒⪻ⅆ⿜⌰⤟ⵣ⏗⸂⚿▚⪪⿐⽻⥝⁹⚎Ⓥ◥◶℀₏Ⅻ` will get matched, but not catched properly.
```lua
print("⭮⽥⻶ⓞ⠏Ⱈ⵼⇠⺀❜⍨ↇ⡧⚏ⷔ⸂␳⋡⒀⻒⪻ⅆ⿜⌰⤟ⵣ⏗⸂⚿▚⪪⿐⽻⥝⁹⚎Ⓥ◥◶℀₏Ⅻ")
```
Will catch: `"⭮⽥⻶ⓞ⠏Ⱈ⵼⇠⺀❜⍨ↇ⡧⚏ⷔ⸂␳⋡⒀⻒⪻ⅆ⿜⌰⤟ⵣ⏗⸂⚿▚⪪⿐⽻⥝⁹⚎Ⓥ◥◶℀₏Ⅻ")`

It returns the unicode with the suffix and `)` but it's not suppose to.

Here's how it looks like:

![image](https://user-images.githubusercontent.com/76539058/137592178-d3699cdc-d172-4228-acfe-e57f819d6cc5.png)

Here is how it should look like:

![image](https://user-images.githubusercontent.com/76539058/137592063-d5aa6d12-eacd-47f7-8348-2f4661cb6d42.png)

**Comment by boatbomber** [comment]
Thanks for bringing this up. In fact, it was not an issue with the Unicode matcher but actually with the string matcher. A fix will be pushed shortly.

**Comment by boatbomber** [comment]
Fixed, thank you!
