### ISSUE TITLE
auto-suggestions

### ISSUE THREAD

**Issue by DodoDeadBird** [boatbomber/Highlighter#36]
i would like a feature that would give you suggestions on the code your typing.
(i tried implenting this on my own and it failed. what i did was basically access the language module and then keep checking if something is similar and then when the user presses TAB it autocompletes it. the cons of whatever i just said is that it does not care if the use is indexing a table). Sorry for bothering and thanks :D

**Comment by boatbomber** [comment]
This is a syntax highlighting module. Implementing auto complete is out of scope for this project. This isn't a code editor, it's a highlighter.
